export const SET_TYPING_VALUE = 'SET_TYPING_VALUE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';
export const SET_USER_REGISTER = 'SET_USER_REGISTER';
export const SET_VALUE_USER = 'SET_VALUE_USER';
export const SET_VALUE_USER_LOGIN = 'SET_VALUE_USER_LOGIN';
export const SUBMIT_LOGIN_USER = 'SUBMIT_LOGIN_USER',